### ISSUE TITLE
Error during build in macos

### ISSUE THREAD

**Issue by sumanchapai** [krishtimil/grapher-c#11]
<img width="1460" alt="Screen Shot 2022-08-09 at 22 42 57" src="https://user-images.githubusercontent.com/26862106/183808396-13fc86bf-e736-4609-a7b0-87730cff0971.png">

**Comment by sumanchapai** [comment]
please note that the test was at this point in repo…
https://github.com/krishtimil/grapher-c/tree/d7b43c609d02e680253b1a84975bd3402c4ee489

**Comment by krishtimil** [comment]
currently have no access to a macOS system to try to fix the issue,  we will get back to you later

**Comment by sumanchapai** [comment]
No worries. I filed a PR.
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26862106/184031426-f3f1c3a9-1cef-4dca-8e78-2af4f4dd90fe.png">
